# Generated by Django 4.2.1 on 2023-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('creator', 'creator'), ('freelancer', 'freelancer')], default='Candidate', max_length=20),
        ),
    ]
