# Generated by Django 4.2.1 on 2023-06-13 12:45

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='jobbids',
            name='date_of_bidding',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 12, 45, 4, 982513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date_of_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
