# Generated by Django 4.2.1 on 2023-07-02 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobbids_date_of_bidding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbids',
            name='date_of_bidding',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 12, 46, 46, 973935, tzinfo=datetime.timezone.utc)),
        ),
    ]
